@hostname = localhost
@port = 8080
@baseUrl = http://{{hostname}}:{{port}}

### ユーザー登録
POST {{baseUrl}}/members
Content-Type: application/json

{
  "username": "yurarara",
  "password": "1234",
  "department": "理工-情報",
  "grade": "B3",
  "student_num": "1111222233334444"
}

### 認証
POST {{baseUrl}}/members
Content-Type: application/json

{
  "username": "yurarara",
  "password": "1234",
}